# Generated by Django 5.0.4 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('plataforma', models.CharField(max_length=250)),
                ('precio', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
