# Generated by Django 5.0.4 on 2024-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(default=1, upload_to='galeria'),
            preserve_default=False,
        ),
    ]
