# Generated by Django 5.0.4 on 2024-06-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_videogames_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogames',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='price',
            field=models.FloatField(),
        ),
    ]
