# Generated by Django 5.0.4 on 2024-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_videogames_amount_alter_videogames_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogames',
            name='video',
            field=models.FileField(default='video', upload_to='galeria'),
        ),
    ]
