# Generated by Django 5.0.4 on 2024-06-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_videogames_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogames',
            name='amount',
        ),
    ]
