# Generated by Django 5.0.4 on 2024-06-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_videogames_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='default description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='description',
            field=models.TextField(default='default description', max_length=1000),
        ),
    ]
