# Generated by Django 5.0.4 on 2024-06-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_description_alter_videogames_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogames',
            name='video',
        ),
    ]
